services:
  mysql:
    image: mysql:8.0                      # MySQL version 8.0  
    restart: always   
    environment:
      MYSQL_ROOT_PASSWORD: "ftn123"           # Set root password (change as needed)
      MYSQL_DATABASE: "social_network"        # Set default database
    ports:
      - "3307:3306"                        # Expose MySQL on port 3306
    command: --init-file /docker-entrypoint-initdb.d/dbinit.sql
    volumes:
      - ./database/dbinit.sql:/docker-entrypoint-initdb.d/dbinit.sql          # Persistent storage for MySQL data
  engine:
    build: 
      context: ./engine
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mysql
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - engine  
volumes:
  mysql:
    driver: local